name: CI/CD Pipeline

on:
  push:
    branches: [staging]
  pull_request:
    branches: [main]
  
permissions:
    actions: read
    contents: read
    security-events: write
    id-token: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'
          
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
          
      - name: Install Frontend Dependencies
        run: npm install
        working-directory: frontend
          
      - name: Install Frontend Dependencies 2
        run: npm install --save-dev @testing-library/react @testing-library/jest-dom
        working-directory: frontend

      - name: Install Frontend Dependencies 3
        run:  npm install react-scripts --save
        working-directory: frontend
        
      - name: Install Backend Dependencies
        run: pip install -r requirements.txt
        working-directory: backend
        
      - name: Run Frontend Tests
        run: npm test
        working-directory: frontend
        
      - name: Run Backend Tests
        run: pytest --cov=./app --cov-report=xml ./tests
        working-directory: backend
        
      - name: Upload Coverage to Codecov
        uses: codecov/codecov-action@v3
        with:
          file: ./backend/coverage.xml

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: javascript, python
          
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3

  build:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: [test, security]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
      - name: Login to Container Registry
        run: |
          az acr login --name ${{ secrets.REGISTRY_NAME }}
          
      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.REGISTRY_NAME }}.azurecr.io/frontend:${{ github.sha }}
          
      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.REGISTRY_NAME }}.azurecr.io/backend:${{ github.sha }}

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: build
    environment: staging
    steps:
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
            
      - name: Deploy Frontend to Staging
        run: |
          az webapp config container set \
            --name ${{ secrets.FRONTEND_APP_NAME }} \
            --slot staging \
            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
            --container-image-name ${{ secrets.REGISTRY_NAME }}.azurecr.io/frontend:${{ github.sha }}
            
      - name: Deploy Backend to Staging
        run: |
          az webapp config container set \
            --name ${{ secrets.BACKEND_APP_NAME }} \
            --slot staging \
            --resource-group ${{ secrets.RESOURCE_GROUP_NAME }} \
            --container-image-name ${{ secrets.REGISTRY_NAME }}.azurecr.io/backend:${{ github.sha }}
